sudo: false
language: python
cache: pip
python: 3.5
script: true
deploy:
  provider: pypi
  user: hellotan
  password: "$password"
env:
  global:
    secure: kjS33VBQKyCzPm0CRVu/pY7+tQyqThwwIbOo7S7n7uc5WcLT375zdm8uzuWa83hTUWUHwDzb7W5FqcSfRlDMiX678rwvipFqeEte9vlIaYLRIlFbnFWut/5WkZwbUVoz8We4FIcbKb6/clleMCb34D3NWHZw/27C+Uxeerl4k5AGYj7uo8GNitJpz45Cn2SpdS/KQq9OHL32ELB+dI5LCXFtGkgE+KvtMdQNJAQvayKDE7ebRIcF9JV1QYdUcrauM/k1IrV/nDeefASZPgmZQToR/WdAO2AM3fHH3tUDya/4wt7B835NZXL/+/i5PA6LrVq2E+016bS1LTpoP+FGjdNmGf13RgwPe1VHveSerlKEL0roxkwZyajkPmYce1gj6MNT8WHzQqoOdWfr3VI6JI/kt1y/PoEckawiyEnxU1eY4khdsg2U8z7Z8YN6Yrcna8PuHKb08HfxDbyiFcEgoJHrjUfAEs5A+jKYDzltS5GNAJslgVmUaITCG+T59nlEqKQ3mBSYG8cgdkvVsP7QCeTbzYjaFsrGtOYGKNCuTF2eewQhJ5Nf5i5Bs/sPF4QnRlRp/fpfOpgH2WM5/047KkQWk7AP0eGHt78+HVAnOutiojGaHoDC84YqFvDCPX6tW5NMUMm1iWZG9oD+0qKVzvx9Lrr6zqw2JwlvDDN0Zvs=
